#!/bin/bash

STANDUP_FILE="$HOME/standup.txt"
BACKUP_FILE="$HOME/standup-prev.txt"

standup_line_count="$( cat $STANDUP_FILE | wc -l )"

if [[ $standup_line_count -gt 0 ]]; then
  exec vim -o \
    "$STANDUP_FILE" \
    "$BACKUP_FILE" \
    "+bufdo set filetype=slack wrap spell" \
    "+b1"
else
  exec vim \
    "$STANDUP_FILE" \
    "+1r $BACKUP_FILE" \
    "+0d" \
    "+set filetype=slack wrap spell"
fi
